version: "3.7"

volumes:
  node_modules:

services:
  app_backend:
    image: "toroinvestimentos/quotesmock"
    ports:
      - 8080:8080

  app_tests:
    build:
      context: .
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    command: yarn test

  app_storybook:
    build:
      context: .
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    command: yarn storybook -p 6006
    ports:
      - 6006:6006

  app_dev:
    build:
      context: .
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    command: yarn start
    ports:
      - 3000:3000
